str="""DB_NAME				   NOT NULL VARCHAR2(8)
 SESSION_KEY					    NUMBER
 SESSION_RECID					    NUMBER
 SESSION_STAMP					    NUMBER
 COMMAND_ID					    VARCHAR2(33)
 START_TIME					    DATE
 END_TIME					    DATE
 INPUT_BYTES					    NUMBER
 OUTPUT_BYTES					    NUMBER
 STATUS_WEIGHT					    NUMBER
 OPTIMIZED_WEIGHT				    NUMBER
 INPUT_TYPE_WEIGHT				    NUMBER
 OUTPUT_DEVICE_TYPE				    VARCHAR2(17)
 AUTOBACKUP_COUNT				    NUMBER
 BACKED_BY_OSB					    VARCHAR2(3)
 AUTOBACKUP_DONE				    VARCHAR2(3)
 STATUS 					    VARCHAR2(23)
 INPUT_TYPE					    VARCHAR2(13)
 OPTIMIZED					    VARCHAR2(3)
 ELAPSED_SECONDS				    NUMBER
 COMPRESSION_RATIO				    NUMBER
 INPUT_BYTES_PER_SEC				    NUMBER
 OUTPUT_BYTES_PER_SEC				    NUMBER
 INPUT_BYTES_DISPLAY				    VARCHAR2(4000)
 OUTPUT_BYTES_DISPLAY				    VARCHAR2(4000)
 INPUT_BYTES_PER_SEC_DISPLAY			    VARCHAR2(4000)
 OUTPUT_BYTES_PER_SEC_DISPLAY			    VARCHAR2(4000)
 TIME_TAKEN_DISPLAY				    VARCHAR2(4000)"""

arg_list=[]
for line in str.splitlines():
    arg_list.append(line.split()[0].strip())

print ','.join(arg_list)


sql="""
SELECT DB_NAME,SESSION_KEY,SESSION_RECID,SESSION_STAMP,COMMAND_ID,
TO_CHAR(START_TIME,'yyyy-mm-dd hh24:mi:ss') START_TIME,
TO_CHAR(END_TIME,'yyyy-mm-dd hh24:mi:ss') END_TIME,
INPUT_BYTES,OUTPUT_BYTES,STATUS_WEIGHT,OPTIMIZED_WEIGHT,INPUT_TYPE_WEIGHT,OUTPUT_DEVICE_TYPE,AUTOBACKUP_COUNT,BACKED_BY_OSB,AUTOBACKUP_DONE,STATUS,INPUT_TYPE,OPTIMIZED,ELAPSED_SECONDS,COMPRESSION_RATIO,INPUT_BYTES_PER_SEC,OUTPUT_BYTES_PER_SEC,INPUT_BYTES_DISPLAY,OUTPUT_BYTES_DISPLAY,INPUT_BYTES_PER_SEC_DISPLAY,OUTPUT_BYTES_PER_SEC_DISPLAY,TIME_TAKEN_DISPLAY FROM RC_RMAN_BACKUP_JOB_DETAILS
WHERE DB_NAME = 'UPGR'
and start_time >= sysdate - 2
;
"""



sql="""
SELECT DB_NAME,SESSION_KEY,SESSION_RECID,SESSION_STAMP,COMMAND_ID,
TO_CHAR(START_TIME,'yyyy-mm-dd hh24:mi:ss') START_TIME,
TO_CHAR(END_TIME,'yyyy-mm-dd hh24:mi:ss') END_TIME,
INPUT_BYTES,OUTPUT_BYTES,STATUS_WEIGHT,OPTIMIZED_WEIGHT,INPUT_TYPE_WEIGHT,OUTPUT_DEVICE_TYPE,AUTOBACKUP_COUNT,BACKED_BY_OSB,AUTOBACKUP_DONE,STATUS,INPUT_TYPE,OPTIMIZED,ELAPSED_SECONDS,COMPRESSION_RATIO,INPUT_BYTES_PER_SEC,OUTPUT_BYTES_PER_SEC,INPUT_BYTES_DISPLAY,OUTPUT_BYTES_DISPLAY,INPUT_BYTES_PER_SEC_DISPLAY,OUTPUT_BYTES_PER_SEC_DISPLAY,TIME_TAKEN_DISPLAY FROM RC_RMAN_BACKUP_JOB_DETAILS
WHERE DB_NAME = 'UPGR'
and start_time >= sysdate - 2
;
"""
