import json



str="""
{"projects":[{"snapdir": "hidden", "default_volblocksize": 8192.0, "defaultgroupquota": 0.0, "logbias": "latency", "creation": "20200708T04:21:38", "nodestroy": false, "snapshots": [], "dedup": false, "sharenfs": "on", "href": "/api/storage/v1/pools/Pool1/projects/default", "sharesmb": "off", "default_permissions": "700", "mountpoint": "/export", "snaplabel": "", "id": "c0328965-7819-edd1-0000-000000000000", "readonly": false, "space_data": 147456.0, "compression": "off", "defaultuserquota": 0.0, "source": {"snapdir": "inherited", "logbias": "inherited", "shareobjectstore": "local", "dedup": "inherited", "sharenfs": "local", "sharesmb": "local", "mountpoint": "local", "compression": "inherited", "sharetftp": "local", "encryption": "local", "sharedav": "local", "copies": "inherited", "aclinherit": "inherited", "shareftp": "local", "readonly": "inherited", "keychangedate": "inherited", "secondarycache": "inherited", "maxblocksize": "inherited", "exported": "local", "vscan": "inherited", "reservation": "local", "atime": "inherited", "recordsize": "inherited", "checksum": "inherited", "sharesftp": "local", "nbmand": "inherited", "aclmode": "inherited", "rstchown": "inherited"}, "default_sparse": false, "encryption": "off", "aclmode": "discard", "copies": 1, "aclinherit": "restricted", "compressratio": 100.0, "shareftp": "", "canonical_name": "Pool1/local/default", "recordsize": 131072.0, "keychangedate": "", "space_available": 68461966344192.0, "secondarycache": "all", "shareobjectstore": "", "name": "default", "space_snapshots": 0.0, "space_unused_res": 0.0, "quota": 0.0, "maxblocksize": 1048576, "exported": true, "default_volsize": 0.0, "vscan": false, "reservation": 0.0, "keystatus": "none", "atime": true, "pool": "Pool1", "default_user": "nobody", "space_unused_res_shares": 0.0, "sharetftp": "", "checksum": "fletcher4", "space_total": 147456.0, "default_group": "other", "sharesftp": "", "rstchown": true, "automatic": {"convert": false, "href": "/api/storage/v1/pools/Pool1/projects/default/automatic"}, "sharedav": "", "nbmand": false},
{"snapdir": "visible", "default_volblocksize": 8192.0, "defaultgroupquota": 0.0, "logbias": "throughput", "creation": "20200708T04:26:13", "nodestroy": false, "snapshots": [], "dedup": false, "sharenfs": "sec=sys,rw,anon=root", "href": "/api/storage/v1/pools/Pool1/projects/GODB", "sharesmb": "off", "default_permissions": "777", "mountpoint": "/export", "snaplabel": "", "id": "cb301b62-86a6-216b-0000-000000000000", "readonly": false, "space_data": 153713012736.0, "compression": "off", "defaultuserquota": 0.0, "source": {"snapdir": "local", "logbias": "local", "shareobjectstore": "local", "dedup": "inherited", "sharenfs": "local", "sharesmb": "local", "mountpoint": "local", "compression": "inherited", "sharetftp": "local", "encryption": "local", "sharedav": "local", "copies": "inherited", "aclinherit": "inherited", "shareftp": "local", "readonly": "inherited", "keychangedate": "inherited", "secondarycache": "inherited", "maxblocksize": "inherited", "exported": "local", "vscan": "inherited", "reservation": "local", "atime": "inherited", "recordsize": "inherited", "checksum": "inherited", "sharesftp": "local", "nbmand": "inherited", "aclmode": "inherited", "rstchown": "local"}, "default_sparse": false, "encryption": "off", "aclmode": "discard", "copies": 1, "aclinherit": "restricted", "compressratio": 100.0, "shareftp": "", "canonical_name": "Pool1/local/GODB", "recordsize": 131072.0, "keychangedate": "", "space_available": 68461966344192.0, "secondarycache": "all", "shareobjectstore": "", "name": "GODB", "space_snapshots": 788682993664.0, "space_unused_res": 0.0, "quota": 0.0, "maxblocksize": 1048576, "exported": true, "default_volsize": 0.0, "vscan": false, "reservation": 0.0, "keystatus": "none", "atime": true, "pool": "Pool1", "default_user": "oracle", "space_unused_res_shares": 0.0, "sharetftp": "", "checksum": "fletcher4", "space_total": 942396006400.0, "default_group": "1002", "sharesftp": "", "rstchown": false, "automatic": {"convert": false, "href": "/api/storage/v1/pools/Pool1/projects/GODB/automatic"}, "sharedav": "", "nbmand": false},
{"snapdir": "hidden", "default_volblocksize": 8192.0, "defaultgroupquota": 0.0, "logbias": "latency", "creation": "20200708T07:15:58", "nodestroy": false, "snapshots": [], "dedup": false, "sharenfs": "on", "href": "/api/storage/v1/pools/Pool1/projects/EXA122V1", "sharesmb": "off", "default_permissions": "700", "mountpoint": "/export", "snaplabel": "", "id": "e8fb7bd7-7e89-c843-0000-000000000000", "readonly": false, "space_data": 442368.0, "compression": "off", "defaultuserquota": 0.0, "source": {"snapdir": "inherited", "logbias": "inherited", "shareobjectstore": "local", "dedup": "inherited", "sharenfs": "local", "sharesmb": "local", "mountpoint": "local", "compression": "inherited", "sharetftp": "local", "encryption": "local", "sharedav": "local", "copies": "inherited", "aclinherit": "inherited", "shareftp": "local", "readonly": "inherited", "keychangedate": "inherited", "secondarycache": "inherited", "maxblocksize": "inherited", "exported": "local", "vscan": "inherited", "reservation": "local", "atime": "inherited", "recordsize": "inherited", "checksum": "inherited", "sharesftp": "local", "nbmand": "inherited", "aclmode": "inherited", "rstchown": "inherited"}, "default_sparse": false, "encryption": "off", "aclmode": "discard", "copies": 1, "aclinherit": "restricted", "compressratio": 100.0, "shareftp": "", "canonical_name": "Pool1/local/EXA122V1", "recordsize": 131072.0, "keychangedate": "", "space_available": 68461966344192.0, "secondarycache": "all", "shareobjectstore": "", "name": "EXA122V1", "space_snapshots": 0.0, "space_unused_res": 0.0, "quota": 0.0, "maxblocksize": 1048576, "exported": true, "default_volsize": 0.0, "vscan": false, "reservation": 0.0, "keystatus": "none", "atime": true, "pool": "Pool1", "default_user": "nobody", "space_unused_res_shares": 0.0, "sharetftp": "", "checksum": "fletcher4", "space_total": 442368.0, "default_group": "other", "sharesftp": "", "rstchown": true, "automatic": {"convert": false, "href": "/api/storage/v1/pools/Pool1/projects/EXA122V1/automatic"}, "sharedav": "", "nbmand": false}]}"""


#
# root = json.loads(str)
#
# for arg in root['projects']:
#     print arg


str2="""
{"filesystems":[{"snapdir": "visible", "logbias": "latency", "creation": "20200708T04:30:55", "nodestroy": false, "dedup": false, "sharenfs": "sec=sys,rw,anon=root", "href": "/api/storage/v1/pools/Pool1/projects/GODB/filesystems/BAK_GODB_01", "sharesmb": "off", "root_acl": ["owner@:rwxpDaARWcCo:allow", "group@:rwxpDaARWc:allow", "everyone@:rwxpDaARWc:allow"], "mountpoint": "/export/BAK_GODB_01", "casesensitivity": "mixed", "snaplabel": "", "id": "f31f4e20-5c94-b6db-0000-000000000000", "readonly": false, "space_data": 155920945152.0, "compression": "off", "sharetftp": "", "source": {"snapdir": "inherited", "logbias": "local", "shareobjectstore": "inherited", "dedup": "inherited", "sharenfs": "inherited", "sharesmb": "inherited", "mountpoint": "inherited", "compression": "inherited", "sharetftp": "inherited", "encryption": "inherited", "sharedav": "inherited", "copies": "inherited", "aclinherit": "inherited", "shareftp": "inherited", "readonly": "inherited", "keychangedate": "inherited", "secondarycache": "inherited", "maxblocksize": "inherited", "exported": "inherited", "vscan": "inherited", "reservation": "local", "atime": "inherited", "recordsize": "inherited", "checksum": "inherited", "sharesftp": "inherited", "nbmand": "inherited", "aclmode": "inherited", "rstchown": "inherited"}, "encryption": "off", "aclmode": "discard", "copies": 1, "aclinherit": "restricted", "compressratio": 100.0, "shareftp": "", "canonical_name": "Pool1/local/GODB/BAK_GODB_01", "recordsize": 131072.0, "keychangedate": "", "space_available": 68450720194560.0, "root_group": "1002", "secondarycache": "all", "root_user": "oracle", "root_permissions": "777", "shareobjectstore": "", "shadow": "none", "space_snapshots": 791886086144.0, "space_unused_res": 0.0, "quota": 0.0, "utf8only": true, "maxblocksize": 1048576, "exported": true, "vscan": false, "reservation": 0.0, "keystatus": "none", "atime": true, "pool": "Pool1", "quota_snap": true, "space_unused_res_shares": 0.0, "name": "BAK_GODB_01", "checksum": "fletcher4", "space_total": 947807031296.0, "project": "GODB", "normalization": "none", "sharesftp": "", "rstchown": false, "reservation_snap": true, "sharedav": "", "nbmand": false},
{"snapdir": "visible", "logbias": "throughput", "creation": "20200708T04:31:06", "nodestroy": false, "dedup": false, "sharenfs": "sec=sys,rw,anon=root", "href": "/api/storage/v1/pools/Pool1/projects/GODB/filesystems/ARC_GODB_01", "sharesmb": "off", "root_acl": ["owner@:rwxpDaARWcCo:allow", "group@:rwxpDaARWc:allow", "everyone@:rwxpDaARWc:allow"], "mountpoint": "/export/ARC_GODB_01", "casesensitivity": "mixed", "snaplabel": "", "id": "5a9f4680-de1f-74bd-0000-000000000000", "readonly": false, "space_data": 5833236480.0, "compression": "lz4", "sharetftp": "", "source": {"snapdir": "inherited", "logbias": "local", "shareobjectstore": "inherited", "dedup": "local", "sharenfs": "inherited", "sharesmb": "inherited", "mountpoint": "inherited", "compression": "local", "sharetftp": "inherited", "encryption": "inherited", "sharedav": "inherited", "copies": "local", "aclinherit": "inherited", "shareftp": "inherited", "readonly": "local", "keychangedate": "inherited", "secondarycache": "local", "maxblocksize": "inherited", "exported": "inherited", "vscan": "local", "reservation": "local", "atime": "local", "recordsize": "local", "checksum": "local", "sharesftp": "inherited", "nbmand": "local", "aclmode": "inherited", "rstchown": "local"}, "encryption": "off", "aclmode": "discard", "copies": 1, "aclinherit": "restricted", "compressratio": 325.0, "shareftp": "", "canonical_name": "Pool1/local/GODB/ARC_GODB_01", "recordsize": 1048576.0, "keychangedate": "", "space_available": 68450720194560.0, "root_group": "1002", "secondarycache": "all", "root_user": "oracle", "root_permissions": "777", "shareobjectstore": "", "shadow": "none", "space_snapshots": 421888.0, "space_unused_res": 0.0, "quota": 0.0, "utf8only": true, "maxblocksize": 1048576, "exported": true, "vscan": false, "reservation": 0.0, "keystatus": "none", "atime": true, "pool": "Pool1", "quota_snap": true, "space_unused_res_shares": 0.0, "name": "ARC_GODB_01", "checksum": "fletcher4", "space_total": 5833658368.0, "project": "GODB", "normalization": "none", "sharesftp": "", "rstchown": false, "reservation_snap": true, "sharedav": "", "nbmand": false},
{"origin": {"project": "GODB", "snapshot": "Daily_Data_20200708_1609", "share": "BAK_GODB_01", "collection": "local", "pool": "Pool1"}, "logbias": "latency", "creation": "20200708T07:20:07", "nodestroy": false, "dedup": false, "sharenfs": "sec=sys,rw,anon=root", "href": "/api/storage/v1/pools/Pool1/projects/GODB/filesystems/CLONE_BAK_GODB_11", "sharesmb": "off", "root_acl": ["owner@:rwxpDaARWcCo:allow", "group@:rwxpDaARWc:allow", "everyone@:rwxpDaARWc:allow"], "mountpoint": "/export/CLONE_BAK_GODB_11", "casesensitivity": "mixed", "snaplabel": "", "id": "a7facec2-6327-9aa9-0000-000000000000", "readonly": false, "space_data": 114688.0, "compression": "off", "sharetftp": "", "source": {"snapdir": "inherited", "logbias": "local", "shareobjectstore": "inherited", "dedup": "inherited", "sharenfs": "inherited", "sharesmb": "inherited", "mountpoint": "local", "compression": "inherited", "sharetftp": "inherited", "encryption": "inherited", "sharedav": "inherited", "copies": "inherited", "aclinherit": "inherited", "shareftp": "inherited", "readonly": "inherited", "keychangedate": "inherited", "secondarycache": "inherited", "maxblocksize": "inherited", "exported": "inherited", "vscan": "inherited", "reservation": "local", "atime": "inherited", "recordsize": "inherited", "checksum": "inherited", "sharesftp": "inherited", "nbmand": "inherited", "aclmode": "inherited", "rstchown": "inherited"}, "encryption": "off", "aclmode": "discard", "copies": 1, "aclinherit": "restricted", "compressratio": 100.0, "shareftp": "", "canonical_name": "Pool1/local/GODB/CLONE_BAK_GODB_11", "recordsize": 131072.0, "keychangedate": "", "space_available": 68450720194560.0, "root_group": "1002", "secondarycache": "all", "root_user": "oracle", "root_permissions": "777", "shareobjectstore": "", "shadow": "none", "space_snapshots": 0.0, "space_unused_res": 0.0, "snapdir": "visible", "quota": 0.0, "utf8only": true, "maxblocksize": 1048576, "exported": true, "vscan": false, "reservation": 0.0, "keystatus": "none", "atime": true, "pool": "Pool1", "quota_snap": true, "space_unused_res_shares": 0.0, "name": "CLONE_BAK_GODB_11", "checksum": "fletcher4", "space_total": 114688.0, "project": "GODB", "normalization": "none", "sharesftp": "", "rstchown": false, "reservation_snap": true, "sharedav": "", "nbmand": false},
{"origin": {"project": "GODB", "snapshot": "Daily_Arch_20200708_1609", "share": "ARC_GODB_01", "collection": "local", "pool": "Pool1"}, "logbias": "throughput", "creation": "20200708T07:20:32", "nodestroy": false, "dedup": false, "sharenfs": "sec=sys,rw,anon=root", "href": "/api/storage/v1/pools/Pool1/projects/GODB/filesystems/CLONE_ARC_GODB_11", "sharesmb": "off", "root_acl": ["owner@:rwxpDaARWcCo:allow", "group@:rwxpDaARWc:allow", "everyone@:rwxpDaARWc:allow"], "mountpoint": "/export/CLONE_ARC_GODB_11", "casesensitivity": "mixed", "snaplabel": "", "id": "a3bccd5f-7d5b-8685-0000-000000000000", "readonly": false, "space_data": 98304.0, "compression": "lz4", "sharetftp": "", "source": {"snapdir": "inherited", "logbias": "local", "shareobjectstore": "inherited", "dedup": "inherited", "sharenfs": "inherited", "sharesmb": "inherited", "mountpoint": "local", "compression": "local", "sharetftp": "inherited", "encryption": "inherited", "sharedav": "inherited", "copies": "local", "aclinherit": "inherited", "shareftp": "inherited", "readonly": "local", "keychangedate": "inherited", "secondarycache": "local", "maxblocksize": "inherited", "exported": "inherited", "vscan": "local", "reservation": "local", "atime": "local", "recordsize": "local", "checksum": "local", "sharesftp": "inherited", "nbmand": "local", "aclmode": "inherited", "rstchown": "local"}, "encryption": "off", "aclmode": "discard", "copies": 1, "aclinherit": "restricted", "compressratio": 100.0, "shareftp": "", "canonical_name": "Pool1/local/GODB/CLONE_ARC_GODB_11", "recordsize": 1048576.0, "keychangedate": "", "space_available": 68450720194560.0, "root_group": "1002", "secondarycache": "all", "root_user": "oracle", "root_permissions": "777", "shareobjectstore": "", "shadow": "none", "space_snapshots": 0.0, "space_unused_res": 0.0, "snapdir": "visible", "quota": 0.0, "utf8only": true, "maxblocksize": 1048576, "exported": true, "vscan": false, "reservation": 0.0, "keystatus": "none", "atime": true, "pool": "Pool1", "quota_snap": true, "space_unused_res_shares": 0.0, "name": "CLONE_ARC_GODB_11", "checksum": "fletcher4", "space_total": 98304.0, "project": "GODB", "normalization": "none", "sharesftp": "", "rstchown": false, "reservation_snap": true, "sharedav": "", "nbmand": false}]}

"""
fs_snap = json.loads(str2)

for fs in  fs_snap['filesystems']:
    print type(fs)
    if 'origin' in  fs.keys():
        print sorted(fs.keys())
        print fs['origin'].keys()
        print fs['origin'].values()
    else:
        print sorted(fs.keys())